from . import product_category
from . import product_uom_category
from . import product_uom
from . import product
from . import sale_order_line
from . import res_partner
from . import sale_order
from . import crm_lead
from . import crm_team
from . import crm_lead_line
from . import stock_location
from . import stock_warehouse
from . import stock_picking
from . import stock_move
from . import stock_inventory_line
from . import stock_inventory_ept
from . import account_tax
